# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Gradle Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/